
package newton;

import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JRadioButton;

/**
 *
 * @author feriv
 */
public class newtonInterpolacion extends javax.swing.JFrame {

    double b0;
    double b1;
    double b2;
    
    double diferenciab2;
    
    double primeras1;
    double primeras2;
    double primeras3;
    
    double segundas1;
    double segundas2;
    
    double terceras1;
    
    double tercerb1;
    double tercerb2;
    double tercerb3;
    double resultadoPrimer;
    double resultadoSegundo;
    double resultadoTercero;
    
    
    double fx;
    
    public newtonInterpolacion() {
        initComponents();
        
        
        gbtn.add(rbtn2);
        gbtn.add(rbtn3);
        gbtn.add(rbtn4);
//        gbtn.add(rbtn5);
        //al inicio solo paso 1 es visible 
        //instrucciones
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
        lbl5.setVisible(false);
        lbl2a.setVisible(false);
        lbl2b.setVisible(false);
//        lbl3a.setVisible(false);
//        lbl3b.setVisible(false);
        
        //paso2
        lblx.setVisible(false);
        //lblfx.setVisible(false);
        lbl0x.setVisible(false);
        lbl1x.setVisible(false);
        lbl2x.setVisible(false);
        lbl3x.setVisible(false);
//        lbl4x.setVisible(false);
        lblf0.setVisible(false);
        lblf1.setVisible(false);
        lblf2.setVisible(false);
        lblf3.setVisible(false);
        //lblf4.setVisible(false);
        
        //txt
        
        txtx2.setVisible(false);
        txtx3.setVisible(false);
       // txtx4.setVisible(false);
        txtx0.setVisible(false);
        txtx1.setVisible(false);
        txtf0.setVisible(false);
        txtf1.setVisible(false);
        txtx.setVisible(false);
        //txtfx.setVisible(false);
        txtf2.setVisible(false);
        txtf3.setVisible(false);
        //txtf4.setVisible(false);
        
        txt5.setVisible(false);
        txt4.setVisible(false);
        //botones
        btnCalcular.setVisible(false);
        btnLimpiar.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtn = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl2a = new javax.swing.JLabel();
        lbl2x = new javax.swing.JLabel();
        lbl3x = new javax.swing.JLabel();
        txtx1 = new javax.swing.JTextField();
        txtx2 = new javax.swing.JTextField();
        lbl2b = new javax.swing.JLabel();
        txtx3 = new javax.swing.JTextField();
        txtx0 = new javax.swing.JTextField();
        lbl0x = new javax.swing.JLabel();
        lbl1x = new javax.swing.JLabel();
        lblf2 = new javax.swing.JLabel();
        lblf3 = new javax.swing.JLabel();
        txtf1 = new javax.swing.JTextField();
        txtf2 = new javax.swing.JTextField();
        txtf3 = new javax.swing.JTextField();
        txtf0 = new javax.swing.JTextField();
        lblf0 = new javax.swing.JLabel();
        lblf1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblx = new javax.swing.JLabel();
        txtx = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        lbl6 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        rbtn4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("POLINOMIO DE INTERPOLACIÓN DE NEWTON");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("1) Elige el número de valores que deseas:");

        lbl2a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2a.setText("a) Inserta tus valores en  X:");

        lbl2x.setText("X2=");

        lbl3x.setText("X3=");

        txtx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtx1ActionPerformed(evt);
            }
        });

        txtx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtx2ActionPerformed(evt);
            }
        });

        lbl2b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2b.setText("b) Inserta tus valores en  f(X):");

        txtx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtx3ActionPerformed(evt);
            }
        });

        txtx0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtx0ActionPerformed(evt);
            }
        });

        lbl0x.setText("X0=");

        lbl1x.setText("X1=");

        lblf2.setText("f(X2)=");

        lblf3.setText("f(X3)=");

        txtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf1ActionPerformed(evt);
            }
        });

        txtf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf2ActionPerformed(evt);
            }
        });

        txtf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf3ActionPerformed(evt);
            }
        });

        txtf0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf0ActionPerformed(evt);
            }
        });

        lblf0.setText("f(X0)=");

        lblf1.setText("f(X1)");

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl3.setText("3) VALORES A ENCONTRAR");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2.setText("2) VALORES ASIGNADOS");

        lblx.setText("X=");

        txtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxActionPerformed(evt);
            }
        });

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl4.setText("4) VALOR INTERPOLADO:");

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl5.setText("5) POLINOMIO DE INTERPOLACIÓN:");

        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });

        lbl6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl6.setText("Elaborado por: Serna Segura Fernanda Ivonne");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        rbtn2.setText("Primer Grado");
        rbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn2ActionPerformed(evt);
            }
        });

        rbtn3.setText("Segundo Grado");
        rbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn3ActionPerformed(evt);
            }
        });

        rbtn4.setText("Tercer Grado");
        rbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lbl3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl0x)
                                .addGap(18, 18, 18)
                                .addComponent(txtx0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl3x)
                                .addGap(18, 18, 18)
                                .addComponent(txtx3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl2x)
                                .addGap(18, 18, 18)
                                .addComponent(txtx2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl1x)
                                .addGap(18, 18, 18)
                                .addComponent(txtx1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblf0)
                                .addGap(18, 18, 18)
                                .addComponent(txtf0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblf3)
                                .addGap(18, 18, 18)
                                .addComponent(txtf3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblf2)
                                .addGap(18, 18, 18)
                                .addComponent(txtf2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblf1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl2a, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl2b, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbl2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rbtn2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn3)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblx)
                        .addGap(18, 18, 18)
                        .addComponent(txtx, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 121, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn2)
                    .addComponent(rbtn4)
                    .addComponent(rbtn3))
                .addGap(15, 15, 15)
                .addComponent(lbl2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2a)
                    .addComponent(lbl2b))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtx0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl0x))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1x)
                            .addComponent(txtx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2x)
                            .addComponent(txtx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl3x)
                            .addComponent(txtx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblf0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblf1)
                            .addComponent(txtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblf2)
                            .addComponent(txtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblf3)
                            .addComponent(txtf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(lbl3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblx)
                    .addComponent(txtx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl5)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(lbl6)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtx1ActionPerformed

    private void txtx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtx2ActionPerformed

    private void txtx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtx3ActionPerformed

    private void txtx0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtx0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtx0ActionPerformed

    private void txtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf1ActionPerformed

    private void txtf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf2ActionPerformed

    private void txtf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf3ActionPerformed

    private void txtf0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf0ActionPerformed

    private void txtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed

    private void rbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn2ActionPerformed
  
        //casos segun 2 datos VISIBLES
        
        //instrucciones
        lbl2.setVisible(!false);
        lbl3.setVisible(!false);
        lbl4.setVisible(!false);
        lbl5.setVisible(!false);
        lbl2a.setVisible(!false);
        lbl2b.setVisible(!false);
//        lbl3a.setVisible(!false);
//        lbl3b.setVisible(!false);
        
        //pasos 2 a
        lbl0x.setVisible(!false);
        lbl1x.setVisible(!false);
        txtx0.setVisible(!false);
        txtx1.setVisible(!false);
        
        //paso 2 b
        lblf0.setVisible(!false);
        lblf1.setVisible(!false);
        txtf0.setVisible(!false);
        txtf1.setVisible(!false);        
        
        //paso 3
        lblx.setVisible(!false);
        //lblfx.setVisible(!false);
        txtx.setVisible(!false);
        //txtfx.setVisible(!false);
     
        //pasos 4 y 5
        txt4.setVisible(!false);
        txt5.setVisible(!false);
        
        //botones
        btnCalcular.setVisible(!false);
        btnLimpiar.setVisible(!false);
        
    //************************************
        //casos segun 2 datos INVISIBLES
    //*************************************
        //pasos 2 a
        lbl2x.setVisible(false);
        lbl3x.setVisible(false);
//        lbl4x.setVisible(false);
        txtx2.setVisible(false);
        txtx3.setVisible(false);
        //txtx4.setVisible(false);
        
        //paso 2 b
        lblf2.setVisible(false);
        lblf3.setVisible(false);
       // lblf4.setVisible(false);
        txtf2.setVisible(false);
        txtf3.setVisible(false); 
        //txtf4.setVisible(false); 
        
             
    }//GEN-LAST:event_rbtn2ActionPerformed

    private void rbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn3ActionPerformed

        //casos segun 3 datos VISIBLES
        
        //instrucciones
        lbl2.setVisible(!false);
        lbl3.setVisible(!false);
        lbl4.setVisible(!false);
        lbl5.setVisible(!false);
        lbl2a.setVisible(!false);
        lbl2b.setVisible(!false);
//        lbl3a.setVisible(!false);
//        lbl3b.setVisible(!false);
        
        //pasos 2 a
        lbl0x.setVisible(!false);
        lbl1x.setVisible(!false);
        lbl2x.setVisible(!false);
        txtx0.setVisible(!false);
        txtx1.setVisible(!false);
        txtx2.setVisible(!false);
        
        //paso 2 b
        lblf0.setVisible(!false);
        lblf1.setVisible(!false);
        lblf2.setVisible(!false);
        txtf0.setVisible(!false);
        txtf1.setVisible(!false); 
        txtf2.setVisible(!false); 
        
        //paso 3
        lblx.setVisible(!false);
        //lblfx.setVisible(!false);
        txtx.setVisible(!false);
        //txtfx.setVisible(!false);
     
        //pasos 4 y 5
        txt4.setVisible(!false);
        txt5.setVisible(!false);
        
        //botones
        btnCalcular.setVisible(!false);
        btnLimpiar.setVisible(!false);
        
    //************************************
        //casos segun 2 datos INVISIBLES
    //*************************************
        //pasos 2 a
        
        lbl3x.setVisible(false);
        //lbl4x.setVisible(false);
        txtx3.setVisible(false);
        //txtx4.setVisible(false);
        
        //paso 2 b
        
        lblf3.setVisible(false);
       // lblf4.setVisible(false);
        txtf3.setVisible(false); 
        //txtf4.setVisible(false);      
        
         
    }//GEN-LAST:event_rbtn3ActionPerformed

    private void rbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn4ActionPerformed
        //casos segun 4 datos VISIBLES
        
        //instrucciones
        lbl2.setVisible(!false);
        lbl3.setVisible(!false);
        lbl4.setVisible(!false);
        lbl5.setVisible(!false);
        lbl2a.setVisible(!false);
        lbl2b.setVisible(!false);
//        lbl3a.setVisible(!false);
//        lbl3b.setVisible(!false);
        
        //pasos 2 a
        lbl0x.setVisible(!false);
        lbl1x.setVisible(!false);
        lbl2x.setVisible(!false);
        lbl3x.setVisible(!false);
        txtx0.setVisible(!false);
        txtx1.setVisible(!false);
        txtx2.setVisible(!false);
        txtx3.setVisible(!false);
        
        //paso 2 b
        lblf0.setVisible(!false);
        lblf1.setVisible(!false);
        lblf2.setVisible(!false);
        lblf3.setVisible(!false);
        txtf0.setVisible(!false);
        txtf1.setVisible(!false); 
        txtf2.setVisible(!false);
        txtf3.setVisible(!false);
        
        //paso 3
        lblx.setVisible(!false);
        //lblfx.setVisible(!false);
        txtx.setVisible(!false);
       // txtfx.setVisible(!false);
     
        //pasos 4 y 5
        txt4.setVisible(!false);
        txt5.setVisible(!false);
        
        //botones
        btnCalcular.setVisible(!false);
        btnLimpiar.setVisible(!false);
        
    //************************************
        //casos segun 4 datos INVISIBLES
    //*************************************
        //pasos 2 
//        lbl4x.setVisible(false);
//        txtx4.setVisible(false);
//        
//        //paso 2 b
//        lblf4.setVisible(false);
//        txtf4.setVisible(false);
    }//GEN-LAST:event_rbtn4ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtx0.setText(" ");
        txtx1.setText(" ");
        txtx2.setText(" ");
        txtx3.setText(" ");
//        txtx4.setText("0");
        txtf0.setText(" ");
        txtf1.setText(" ");
        txtf2.setText(" ");
        txtf3.setText(" ");
       // txtf4.setText("0");
        txtx.setText(" ");
       // txtfx.setText(" ");
        txt4.setText(" ");
        txt5.setText(" ");
       
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        

        double x=Double.parseDouble(txtx.getText());
        
        
        //método
       //metodoNewton(x0,x1,x2,x3,x4,fx0,fx1,fx2,fx3,fx4);
       metodoNewton(x);
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed
    //private void metodoNewton(double mx0,double mx1,double mx2,double mx3,double mx4,double mfx0,double mfx1,double mfx2,double mfx3,double mfx4){
    private void metodoNewton(double mx){
       //puntpo 2a
        
        double x0=Double.parseDouble(txtx0.getText());
        double x1=Double.parseDouble(txtx1.getText());
        double x2=Double.parseDouble(txtx2.getText());
        double x3=Double.parseDouble(txtx3.getText());
        //double x4=Double.parseDouble(txtx4.getText());
        
        //punto 2 b
        double fx0=Double.parseDouble(txtf0.getText());
        double fx1=Double.parseDouble(txtf1.getText());
        double fx2=Double.parseDouble(txtf2.getText());
        double fx3=Double.parseDouble(txtf3.getText());
      

       b0=fx0;
       //*******************************************************
       //dos terminos
       b1=(fx1-fx0)/(x1-x0);
       
       //*******************************************************
            //tres terminos
       //*******************************************************
       diferenciab2= ((fx2-fx1)/(x2-x1));
       b2=(diferenciab2-b1)/(x2-x0);
                 
       //*******************************************************
                    //cuatro terminos
       //*******************************************************
    //primeras diferencias
       primeras1 = b1;
       primeras2= diferenciab2;
       primeras3=((fx3-fx2)/(x3-x2));
    //segundas diferencias
    
        segundas1=(primeras2-primeras1)/(x2-x0);
        segundas2= (primeras3-primeras2) /(x3-x1);
    //terceras diferencias
        terceras1= (segundas2-segundas1)/(x3-x0);
        
        //asignacion de valores
        tercerb1=b1;
        tercerb2=segundas1;
        tercerb3=terceras1;
        //FORMULA
        
 
       //calculando Valor Primer grado
        
       
       //Calculando
        //********************************************
          //para primer grado
        //********************************************
       if(rbtn2.isSelected()==true){
           resultadoPrimer=new BigDecimal(b0+b1*(mx-x0))
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(resultadoPrimer));
           System.out.println("El valor Interpolado es: "+resultadoPrimer);
           
           //para polinomio
          
          double  polinomioPrimer= new BigDecimal( b0+(b1*(-x0)))
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(resultadoPrimer));
       
       double  polinomiox= new BigDecimal( b1)
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(resultadoPrimer));
               
       txt5.setText(String.valueOf(polinomioPrimer)+String.valueOf(polinomiox)+'x');
           System.out.println("El polinomio de Interpolación es: "+String.valueOf(polinomioPrimer)+String.valueOf(polinomiox)+'x');
           
           
       }
       
        //********************************************
          //para segundo grado
        //********************************************
       else if(rbtn3.isSelected()==true){
           resultadoSegundo=new BigDecimal(b0+b1*(mx-x0)+b2*(mx-x0)*(mx-x1))
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(resultadoSegundo));
       System.out.println("El valor Interpolado es: "+resultadoSegundo);
       
          //para polinomio
          //término numerico
          double  polinomioPrimer= new BigDecimal( b0+(b1*(-x0))+(b2*(-x0)*(-x1)))
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(polinomioPrimer));
       
       //termino lineal
       double  polinomiox= new BigDecimal( b1+b2)
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(polinomiox));
       
       //termino cuadrado
       double  polinomiox2= new BigDecimal(b2)
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(polinomiox2));
               
       txt5.setText(String.valueOf(polinomioPrimer)+String.valueOf(polinomiox)+'x'+String.valueOf(polinomiox2)+"x^2");
           System.out.println("El valor Interpolado es: "+String.valueOf(polinomioPrimer)+String.valueOf(polinomiox)+"x"+String.valueOf(polinomiox2)+"x^2");
       
       }
       else if(rbtn4.isSelected()==true){
           resultadoTercero=new BigDecimal(b0+tercerb1*(mx-x0)+tercerb2*(mx-x0)*(mx-x1)+tercerb3*(mx-x0)*(mx-x1)*(mx-x2))
               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       txt4.setText(String.valueOf(resultadoTercero));
       System.out.println("El valor Interpolado es: "+resultadoTercero);
       }
       //
       
       //vallores
        System.out.println("************************************************");
        System.out.println("VALORES EN X:");
        System.out.println("************************************************");
        System.out.println("Valor en x0= "+x0);
        System.out.println("Valor en x1= "+x1);
        System.out.println("Valor en x2= "+x2);
        System.out.println("Valor en x3= "+x3);
        System.out.println("************************************************");
        System.out.println("VALORES EN f(X):");
        System.out.println("************************************************");
        System.out.println("Valor en fx0= "+fx0);
        System.out.println("Valor en fx1= "+fx1);
        System.out.println("Valor en fx2= "+fx2);
        System.out.println("Valor en fx3= "+fx3);
        System.out.println("************************************************");
        System.out.println("Asignación de Valores:");
        System.out.println("************************************************");
        System.out.println("El valor de b0 es : "+b0);
        System.out.println("El valor de b1 es : "+b1);
        System.out.println("El valor de b2 es : "+b2);
        System.out.println("El valor de b3 es : "+tercerb3);
        
        
        
       
        
        

       
       
       
       
      
      
       
       
//       (b0+b1*(x-mx0))
//       double resultadoInterpolado=new BigDecimal(b0-(b1*(x-mx0))+(b2*(x-mx0)*(x-mx1))+(b3*(x-mx0)*(x-mx1)*(x-mx2))+(b4*(x-mx0)*(x-mx1)*(x-mx2)*(x-mx3)))
//               .setScale(4, RoundingMode.HALF_EVEN).doubleValue();
//       double resultadoPolinomio=new BigDecimal(b0+b1*(x-mx0)).setScale(4, RoundingMode.HALF_EVEN).doubleValue();
       
       
       
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newtonInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newtonInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newtonInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newtonInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newtonInterpolacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup gbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl0x;
    private javax.swing.JLabel lbl1x;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl2a;
    private javax.swing.JLabel lbl2b;
    private javax.swing.JLabel lbl2x;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl3x;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lblf0;
    private javax.swing.JLabel lblf1;
    private javax.swing.JLabel lblf2;
    private javax.swing.JLabel lblf3;
    private javax.swing.JLabel lblx;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txtf0;
    private javax.swing.JTextField txtf1;
    private javax.swing.JTextField txtf2;
    private javax.swing.JTextField txtf3;
    private javax.swing.JTextField txtx;
    private javax.swing.JTextField txtx0;
    private javax.swing.JTextField txtx1;
    private javax.swing.JTextField txtx2;
    private javax.swing.JTextField txtx3;
    // End of variables declaration//GEN-END:variables
}
